source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

def cocoating_pods
    pod 'CocoaAsyncSocket'
end
target 'Fastlane-OC' do
    cocoating_pods
end


#target 'YiFu' do
#    cocoating_pods
#end
#target 'QiGuanJia' do
#    cocoating_pods
#end
#target 'FuWei' do
#    cocoating_pods
#end
#target 'HaoYingGuoJi' do
#    cocoating_pods
#end
